### ISSUE TITLE
Fetching and displaying user information.

### ISSUE THREAD

**Issue by CollinPhan** [SWP391-Nhom-4-NET1803/FE_Code_Main#48]

**Comment by SpaceStalinn** [comment]
Displaying list of all users for system admin

![Screenshot (901)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/2e9e6abb-29c7-470f-bdde-924433414067)
![Screenshot (902)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/085b6a20-7c1f-450c-9af9-866a5df19f59)

**Comment by SpaceStalinn** [comment]
Adding user in system admin dashboard
![Screenshot (903)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/92723ce0-1992-4eb9-901a-4f6c4abc1c73)
![Screenshot (911)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/9393fea8-27ca-4481-a96a-4b25bb0bbfa6)
![Screenshot (905)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/28258972-af54-48f9-bc85-45a5f4e18fa0)

**Comment by SpaceStalinn** [comment]
Updating user status



![Screenshot (908)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/09a5a898-ca3e-49e8-b065-4dde327b9e50)
![Screenshot (909)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/540c390c-9876-405c-aee8-24e46dffa14c)
![Screenshot (910)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/9a6d86cf-2235-43b5-a10e-50f7ca3bd8cc)

**Comment by SpaceStalinn** [comment]
Displaying user data in profile
![Screenshot (915)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/d1f6f494-584c-45a0-8154-3a715e76b4c1)
![Screenshot (916)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/641f98b0-cfa3-4b3e-9ac7-d8b9f6098b39)
![Screenshot (918)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/75f6e1be-3016-4171-b8c1-927d067473fe)

**Comment by SpaceStalinn** [comment]
Fetching user data in account page
![Screenshot (920)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/2169bf24-4b89-4667-9202-cbf6d7675934)
![Screenshot (921)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/54f06740-92ee-4dd8-aa1b-3d41d94a1f82)
