### ISSUE TITLE
Try register a clinic

### ISSUE THREAD

**Issue by CollinPhan** [SWP391-Nhom-4-NET1803/FE_Code_Main#51]

**Comment by SpaceStalinn** [comment]
Test status: Success? ~~
-----------------------------------------------------------------------------
Test data: 
{
  "OwnerId": 2,
  "Name": "Phòng khám Nụ cười",
  "Description": "",
  "Address": "21B Đường 297, Phước Long B, Thủ Đức, Hồ Chí Minh",
  "Phone": "0984929046",
  "Email": "baotdqse183377@fpt.edu.vn",
  "OpenHour": "07:00:00.0000000",
  "CloseHour": "17:00:00.0000000",
  "ClinicServices": [
    16,
    4,
    1,
    2,
    5,
    7,
    9
  ],
  "ClinicSlots": [
    {
      "slotId": 0,
      "maxAppointments": 0
    }
  ]
}
-----------------------------------------------------------------------------
Mà cái owner ID là phải là owner trước rồi mới được đăng kí hả ông.

-----------------------------------------------------------------------------
Screenshot 
![Screenshot (893)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/b17caba7-4a9c-46a6-bc72-9ea9e80e35b6)
![Screenshot (894)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/e7201bd1-10b0-4edb-8dbc-4fb1718460e6)
![Screenshot (895)](https://github.com/SWP391-Nhom-4-NET1803/FE_Code_Main/assets/125347214/53a1d5bd-4617-4c28-8eb7-52f6f4b6ec06)

**Comment by SpaceStalinn** [comment]
Với cái api nào để booking vậy ông tui mò không thấy.
